import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://reginsaqa.sunedu.gob.pe/#/home');
  await page.getByRole('button', { name: 'Acceder Ahora' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('lizvidal');
  await page.getByRole('textbox', { name: 'Usuario' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('QA');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('QA1234510qa');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('link', { name: ' Infractor y Sanción' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.locator('#pn_id_15').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('6', { exact: true }).click();
  await page.getByRole('columnheader', { name: 'F. Registro' }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('.p-element.p-ripple.p-button-rounded.p-button-warning').first().click();
  await page.getByRole('button', { name: 'Editar cabecera' }).click();
  await page.locator('.p-checkbox-box').first().click();
  await page.getByText('Seleccionar archivo').nth(1).click();
  await page.locator('span').filter({ hasText: 'Seleccionar archivo' }).nth(2).setInputFiles('GENERAL N° 00001-2026-SUNEDU-SG-OTI.pdf');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Reconsid N° 1554-2026');
  await page.getByRole('button', { name: 'Choose Date' }).nth(1).click();
  await page.getByText('20', { exact: true }).click();
  await page.getByRole('button', { name: 'Guardar cabecera' }).click();
  await page.getByRole('tab', { name: 'Detalle de sanciones' }).click();
  await page.getByRole('button').nth(4).click();
  await page.locator('.flex.flex-column.gap-2 > div > .p-element > .p-checkbox > .p-checkbox-box').first().click();
  await page.locator('.flex.flex-column.gap-3 > div:nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box').click();
  await page.locator('#pn_id_165').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Día' }).click();
  await page.getByPlaceholder('Cantidad').click();
  await page.getByPlaceholder('Cantidad').click();
  await page.getByPlaceholder('Cantidad').click();
  await page.getByPlaceholder('Cantidad').click();
  await page.getByPlaceholder('Cantidad').fill('1');
  await page.locator('.flex.flex-column.gap-2 > div:nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box').click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('div').filter({ hasText: 'ÉxitoDetalle guardado' }).nth(5).click();
  await page.getByRole('button', { name: 'Profile' }).click();
  await page.locator('a').filter({ hasText: 'Sign Out20 Jan 2026 04:23:00 PM GMT-' }).click();
  await page.getByRole('button', { name: 'Si' }).click();
});